language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-wagtail' ]; then cd .. && eval "mv $currentfolder generator-wagtail" && cd generator-wagtail; fi

